{host, ...}: let
  inherit
    (import ../../hosts/${host}/variables.nix)
    browser
    terminal
    ;
in {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$modifier,Return,exec,${terminal}"
      "$modifierSHIFT,Return,exec,rofi -show drun"
      "$modifierSHIFT,W,exec,web-search"
      "$modifierALT,W,exec,wallsetter"
      "$modifierSHIFT,N,exec,swaync-client -rs"
      "$modifierSHIFT,M,exec,task-waybar"
      "$modifier,W,exec,zen"
      "$modifier,E,exec,emopicker9000"
      "$modifier,S,exec,screenshootin"
      "$modifierSHIFT,C,exec,hyprpicker -a"
      "$modifier,T,exec,pypr toggle term"
      "$modifierSHIFT,T,exec,pypr toggle thunar"
      "$modifier,C,exec,slack"
      "$modifier,V,exec,cursor"
      "$modifier,Q,killactive,"
      "$modifier,P,exec,pypr toggle volume"
      "$modifier,B,exec,pypr toggle bluetooth"
      "$modifierSHIFT,B,exec,beeper"
      "$modifierSHIFT,I,togglesplit,"
      "$modifier,F,fullscreen,"
      "$modifierSHIFT,F,togglefloating,"
      "$modifierSHIFT,Q,exit,"
      "$modifierSHIFT,left,movewindow,l"
      "$modifierSHIFT,right,movewindow,r"
      "$modifierSHIFT,up,movewindow,u"
      "$modifierSHIFT,down,movewindow,d"
      "$modifierSHIFT,h,movewindow,l"
      "$modifierSHIFT,l,movewindow,r"
      "$modifierSHIFT,k,movewindow,u"
      "$modifierSHIFT,j,movewindow,d"
      "$modifier,left,movefocus,l"
      "$modifier,right,movefocus,r"
      "$modifier,up,movefocus,u"
      "$modifier,down,movefocus,d"
      "$modifier,h,movefocus,l"
      "$modifier,l,movefocus,r"
      "$modifier,k,movefocus,u"
      "$modifier,j,movefocus,d"
      "$modifier,1,workspace,1"
      "$modifier,2,workspace,2"
      "$modifier,3,workspace,3"
      "$modifier,4,workspace,4"
      "$modifier,5,workspace,5"
      "$modifier,6,workspace,6"
      "$modifier,7,workspace,7"
      "$modifier,8,workspace,8"
      "$modifier,9,workspace,9"
      "$modifier,0,workspace,10"
      "$modifierSHIFT,SPACE,movetoworkspace,special"
      "$modifier,SPACE,togglespecialworkspace"
      "$modifierSHIFT,1,movetoworkspace,1"
      "$modifierSHIFT,2,movetoworkspace,2"
      "$modifierSHIFT,3,movetoworkspace,3"
      "$modifierSHIFT,4,movetoworkspace,4"
      "$modifierSHIFT,5,movetoworkspace,5"
      "$modifierSHIFT,6,movetoworkspace,6"
      "$modifierSHIFT,7,movetoworkspace,7"
      "$modifierSHIFT,8,movetoworkspace,8"
      "$modifierSHIFT,9,movetoworkspace,9"
      "$modifierSHIFT,0,movetoworkspace,10"
      "$modifierCONTROL,right,workspace,e+1"
      "$modifierCONTROL,left,workspace,e-1"
      "$modifier,mouse_down,workspace, e+1"
      "$modifier,mouse_up,workspace, e-1"
      "$modifier,mouse:272,movewindow"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "$modifier, mouse:272, movewindow"
      "$modifier, mouse:273, resizewindow"
    ];
  };
}
